// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYdD0J2xh8EkF_8XYHwZ7-HihzX919gCE',
    appId: '1:147117607985:web:a8228ee5da1372ea4e1910',
    messagingSenderId: '147117607985',
    projectId: 'reddit-clone-8f5f6',
    authDomain: 'reddit-clone-8f5f6.firebaseapp.com',
    storageBucket: 'reddit-clone-8f5f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFCaefVTxY01rjk0V4H9JH45yddwXxA4',
    appId: '1:147117607985:android:62179e41353c46914e1910',
    messagingSenderId: '147117607985',
    projectId: 'reddit-clone-8f5f6',
    storageBucket: 'reddit-clone-8f5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQylIJ5EdcYERRrcnUe4XSNYJjJ3qbANs',
    appId: '1:147117607985:ios:3dd65b988f8094204e1910',
    messagingSenderId: '147117607985',
    projectId: 'reddit-clone-8f5f6',
    storageBucket: 'reddit-clone-8f5f6.appspot.com',
    iosClientId: '147117607985-a76kpi2bnjeeg7h62o30vk0fu8sq5d1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
